[Do not review] Added Identity Hub base
agera-edc/IdentityHubOld pull request #1
Opened 2022-06-03 08:01 UTC by ouphi

2022-06-03 12:27 UTC, algattik commented on extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/dtos/FeatureDetection.java
> +        return interfaces;
should be immutable.

2022-06-03 12:27 UTC, algattik commented on extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/dtos/FeatureDetection.java
> +    private List<Object> interfaces;
why Object and not Strings?

2022-06-03 12:31 UTC, algattik commented on extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/featuredetection/FeatureDetectionTests.java
> +        var expectedFeatureDetection = new FeatureDetection.Builder().build();
would probably be cleaner to use the client type here. Then you would also explicitly write out what the expected `type` is

2022-06-03 12:32 UTC, algattik requested changes
comments

2022-06-03 12:35 UTC, marcgs commented on extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/dtos/FeatureDetection.java
> +    private List<Object> interfaces;
I think it will contain another level of items (https://identity.foundation/decentralized-web-node/spec/#feature-detection):

```
{
  interfaces: {
     collections: ["CollectionsQuery", "CollectionsWrite"]
  }
}
```

2022-06-03 12:39 UTC, ouphi commented on extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/dtos/FeatureDetection.java
> +    private List<Object> interfaces;
It is a first version where I didn't implement the real data model of interface, that why I added the "// TODO: Implement interface data model https://identity.foundation/decentralized-web-node/spec/#interfaces"
As discussed, created an empty WebNodeInterface class to make it clearer.

2022-06-03 12:39 UTC, marcgs commented on docs/developer/openapi.md
> +./gradlew rest-client:clean rest-client:build
This is required when cloning the project so that it compiles. I think we should add it to the README.

2022-06-03 12:40 UTC, marcgs commented on extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/featuredetection/FeatureDetectionTests.java
> +import java.util.ArrayList;
Unused import

2022-06-03 12:43 UTC, marcgs approved these changes

2022-06-03 12:45 UTC, Izzzu commented on extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/dtos/FeatureDetection.java
> +public class FeatureDetection {
Javadoc is missing

2022-06-03 12:59 UTC, ouphi commented on extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/featuredetection/FeatureDetectionTests.java
> +import java.util.ArrayList;
It is used

2022-06-03 15:05 UTC, pkirch commented on docs/developer/openapi.md
> +./gradlew clean resolve
This command is failing on my side. Am I missing something? See gradle output.

```shell
> Task :extensions:identity-hub:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extensions:identity-hub:compileJava'.
       - file:/C:/Users/pkirch/.m2/repository/org/eclipse/dataspaceconnector/http/0.0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/pkirch/.m2/repository/org/eclipse/dataspaceconnector/http/0.0.1-SNAPSHOT/http-0.0.1-SNAPSHOT.pom
       - https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/org/eclipse/dataspaceconnector/http/0.0.1-SNAPSHOT/maven-metadata.xml
       - https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/org/eclipse/dataspaceconnector/http/0.0.1-SNAPSHOT/http-0.0.1-SNAPSHOT.pom
     Required by:
         project :extensions:identity-hub

```

2022-06-03 15:18 UTC, ouphi commented on docs/developer/openapi.md
> +./gradlew clean resolve
I added the instructions to publish edc artifact locally.
Let me know if it resolves the problem :)

2022-06-03 15:24 UTC, pkirch commented on extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/featuredetection/FeatureDetectionTests.java
> +    final String API_URL = "http://localhost:8181/api";
Should constants like this be `static`?

2022-06-03 15:24 UTC, pkirch commented on build.gradle.kts
> +plugins {
Does this file need a copyright header, too?

(Same question for `settings.gradle.kts`.)

2022-06-07 09:20 UTC, ouphi commented on docs/developer/openapi.md
> +./gradlew clean resolve
@pkirch as you are in vacation I close this comment for now, but we can sync and double check when you are back.

2022-06-07 11:50 UTC, algattik commented on README.md
> +To be able to compile and run this project, you need to follow the [open api instructions](docs/developer/openapi.md) to generate the OpenAPI `yaml` file and generate a REST client.
actually not, the yaml file is in version control, and the client is built automatically, right?

2022-06-07 11:52 UTC, algattik commented on extensions/identity-hub/src/test/java/org/eclipse/dataspaceconnector/identityhub/api/featuredetection/FeatureDetectionTests.java
> +        var expectedFeatureDetection = new FeatureDetection().type("FeatureDetection").interfaces(new ArrayList<>());
nit: 
```suggestion
        var expectedFeatureDetection = new FeatureDetection().type("FeatureDetection").interfaces(List.of());
```

2022-06-07 11:52 UTC, algattik commented on extensions/identity-hub/src/main/java/org/eclipse/dataspaceconnector/dtos/FeatureDetection.java
> +            featureDetection.interfaces = interfaces;
unmodifiable

2022-06-07 12:09 UTC, ouphi commented on README.md
> +To be able to compile and run this project, you need to follow the [open api instructions](docs/developer/openapi.md) to generate the OpenAPI `yaml` file and generate a REST client.
This is to be able to develop locally as the IDE will have errors. I updated the readme to make it clearer.

2022-06-07 12:09 UTC, algattik approved these changes

2022-06-07 13:00 UTC, merged