ADR for Identity Hub
agera-edc/IdentityHubOld pull request #2
Opened 2022-06-08 10:39 UTC by marcgs

closes #208

ADR for Indentity Hub architecture for MVD.

2022-06-08 12:35 UTC, algattik requested changes

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +An identity hub is a credential storage and message relay system run by a dataspace participant. In particular, the identity hub will be used to securely deliver [verifiable credentials](https://www.
to avoid confusion we should point out that we do not use a message relay

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +An identity hub is a credential storage and message relay system run by a dataspace participant. In particular, the identity hub will be used to securely deliver [verifiable credentials](https://www.
what is a verifiable presentation?

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The [Identity Hub specification](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md) provides an extensive description of different aspects that need to be supported by
I don't think we should create links to personal repos in ADRs

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +Each participant in the dataspace will have a single identity and a single Identity Hub instance available (no namespacing required). The Identity Hub endpoints will not be secured with any kind of a
spelling 'auth'

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +Each participant in the dataspace will have a single identity and a single Identity Hub instance available (no namespacing required). The Identity Hub endpoints will not be secured with any kind of a
what is "an identity"?

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +![Authorization](authorization.png)
since we are splitting out the response arrow in other requests, should we also split out arrow 2 into request and response?

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +![Authorization](authorization.png)
is 5 verifiable credentials or verifiable presentations?

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +![Onboarding](onboarding.png)
should "Self-description document" be removed here?

2022-06-08 12:35 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The Identity Hub will be developed as an EDC extension and will be deployed as a [collocated test deployment](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#1-colloc
as above (link to personal repo)

2022-06-08 13:11 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The [Identity Hub specification](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md) provides an extensive description of different aspects that need to be supported by
Its the only source we have for the overall spec. Not sure if we have an alternative for now.

2022-06-08 13:12 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +An identity hub is a credential storage and message relay system run by a dataspace participant. In particular, the identity hub will be used to securely deliver [verifiable credentials](https://www.
Added link to spec

2022-06-08 13:14 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +Each participant in the dataspace will have a single identity and a single Identity Hub instance available (no namespacing required). The Identity Hub endpoints will not be secured with any kind of a
Added link

2022-06-08 13:25 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +![Onboarding](onboarding.png)
I did and added a few more improvements to consolidate both diagrams

2022-06-08 13:25 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The Identity Hub will be developed as an EDC extension and will be deployed as a [collocated test deployment](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#1-colloc
see my comment before

2022-06-08 17:31 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The [Identity Hub specification](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md) provides an extensive description of different aspects that need to be supported by
how about just removing the sentence then? We can put that e.g. in an issue instead

2022-06-08 17:31 UTC, algattik commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The Identity Hub will be developed as an EDC extension and will be deployed as a [collocated test deployment](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#1-colloc
here also, why not extract from the linked document the necessary information to make this document standalone?

2022-06-09 06:29 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +The [Identity Hub specification](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md) provides an extensive description of different aspects that need to be supported by
Ok I have removed all references to the private repository

2022-06-09 07:44 UTC, algattik requested changes
I've pushed some changes.
"Verifiable credentials" and "presentations" are used seemingly interchangeably, and in one case contradictorily in one diagram and its legend. Could we clarify?

2022-06-09 12:15 UTC, algattik approved these changes

2022-06-09 13:35 UTC, Izzzu commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +During participant-to-participant communication via IDS REST, the request destination participant queries the Verifiable Presentations of the request originator participant. According to the policies
nit:
```suggestion
During participant-to-participant communication via IDS REST, the request destination participant queries the Verifiable Presentations of the request originator participant. Access to resources is granted or denied according to the policies in place and the available Verifiable Presentations.
```
it's easier to understand this sentence this way IMHO but feel free to disregard.

2022-06-09 13:37 UTC, Izzzu approved these changes

2022-06-09 16:41 UTC, cpeeyush commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +An identity hub is a credential storage and message relay system run by a dataspace participant. In particular, the identity hub will be used to securely deliver [Verifiable Credentials](https://www.
nit: do you mean here that identity hub can also be used as message relay system ? Because in the last line of this paragraph we also say that this will not be used as a message relay system.

2022-06-09 16:57 UTC, cpeeyush approved these changes

2022-06-09 16:59 UTC, marcgs commented on docs/developer/decision-records/2022-06-08-identity-hub/README.md
> +An identity hub is a credential storage and message relay system run by a dataspace participant. In particular, the identity hub will be used to securely deliver [Verifiable Credentials](https://www.
Yes, I mean that by design it can, but its not the way we will use it in the MVD.

2022-06-09 16:59 UTC, merged